times_eat = int(input('How many times a week do you eat at the student cafeteria?'))
lunch_price = float(input('The price of a typical student lunch?'))
weekly_groceries = float(input('How much money do you spend on groceries in a week?'))
print('Average food expenditure:')
print('Daily:', (times_eat * lunch_price + weekly_groceries) / 7, 'euros')
print('Weekly:', (times_eat * lunch_price + weekly_groceries), 'euros')
