given_name = input('Given name: ')
family_name = input('Family name: ')
street_address = input ('Street address: ')
city_and_zip = input('City and postal code: ')
print(given_name + ' ' + family_name)
print(street_address)
print(city_and_zip)
